export const skills = [
    { name: "Rust", logo: "/skill/rust.svg" },
    { name: "Axum", logo: "/skill/rust.svg" },
    { name: "Tokio", logo: "/skill/tokio.svg" },
    { name: "Python", logo: "/skill/python2.png" },
    { name: "FastAPI", logo: "/skill/fastapi.png" },
    { name: "Laravel", logo: "/skill/laravel.png" },
    { name: "Keycloak", logo: "/skill/kc.png" },
    { name: "RestAPI", logo: "/skill/rest.png" },
    { name: "GRPC", logo: "/skill/grpc.png" },
    { name: "WebSocket", logo: "/skill/ws.png" },
    { name: "GraphQL", logo: "/skill/graphql.png" },
    { name: "Next.js", logo: "/skill/nextjs.jpg" },
    { name: "React", logo: "/skill/react.png" },
    { name: "TypeScript", logo: "/skill/ts.png", color: "#3178c6", textColor: "#fff" },
    { name: "Tailwind", logo: "/skill/tailwind.png" },
    { name: "Shadcn", logo: "/skill/shadcn.jpg" },
    { name: "Material UI", logo: "/skill/mui.png" },
    { name: "PyTorch", logo: "/skill/pytorch.png" },
    { name: "Tensorflow", logo: "/skill/tf.png" },
    { name: "Keras", logo: "/skill/keras.png", color: "#d00000", textColor: "#fff" },
    { name: "Numpy", logo: "/skill/numpy.png" },
    { name: "Pandas", logo: "/skill/pandas.png" },
    { name: "SkLearn", logo: "/skill/sklearn.svg" },
    { name: "Matplotlib", logo: "/skill/plt.png" },
    { name: "Google Collaboratory", logo: "/skill/colab.png" },
    { name: "Kaggle", logo: "/skill/kaggle.png" },
    { name: "Media Pipe", logo: "/skill/mediapipe.png" },
    { name: "OpenCV", logo: "/skill/opencv.png" },
    { name: "PostgreSQL", logo: "/skill/pg.png" },
    { name: "MySQL", logo: "/skill/mysql.png" },
    { name: "Redis", logo: "/skill/redis.png" },
    { name: "SQLite", logo: "/skill/sqlite.png" },
    { name: "S3", logo: "/skill/s3.png" },
    { name: "Minio", logo: "/skill/minio.webp" },
    { name: "Ubuntu", logo: "/skill/ubuntu.webp" },
    { name: "Docker", logo: "/skill/docker.png" },
    { name: "Nginx", logo: "/skill/nginx.jpg" },
    { name: "Git", logo: "/skill/git.avif" },
    { name: "Gitlab CI", logo: "/skill/gitlabci.png" },
    { name: "Kubernetes", logo: "/skill/k8s.png" },
    { name: "Grafana", logo: "/skill/grafana.jpg" },
    { name: "Open Telemetry", logo: "/skill/otel.png" },
    { name: "Beszel", logo: "/skill/beszel.webp" },
    { name: "Cloudflare", logo: "/skill/cf.png" },
    { name: "Redis Pub Sub", logo: "/skill/pubsub.avif" },
    { name: "Selenium", logo: "/skill/selenium.webp" },
]

export const getSkills = (names: string[]) => {
    return skills.filter(skill => names.includes(skill.name))
}